name: Flask Web App Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Get code
        uses: actions/checkout@v4  # Use to download our repository,s code into Github actions runner.

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Test application
        run: |
          python -m py_compile fapp.py

      - name: Build
        run: echo "Build successful"

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "fapp.py,requirements.txt"
          target: "/home/ubuntu/fapp"

      - name: Run application on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
             cd /home/ubuntu/fapp
             pip3 install -r requirements.txt --break-system-packages  
             nohup python3 fapp.py > app.log 2>&1 &
             
      - name: Show application URL
        run: |
          echo "Application deployed successfully!"
          echo "Open: http://${{ secrets.EC2_HOST }}:5000"
