name: Docker File

on:
  workflow_dispatch:

jobs:
  docker:
     runs-on: ubuntu-latest

 steps:
  - name: Get Code
    uses: actions/checkout@v4

  - name: Build Docker Image
    run: docker build -t flask-app .

  - name: Docker Container
    run: docker run -d -p 5000:5000 flask-app

  - name: Test Apllication
    run: |
         sleep 5
         curl http://localhost:5000
